apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: python-app
spec:
  maxReplicas: 5
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: python-app
  targetCPUUtilizationPercentage: 60
status:
  currentReplicas: 0
  desiredReplicas: 0
